{% set name = "hera" %}
{% set version = "5.13.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hera-{{ version }}.tar.gz
  sha256: f58f9c6823e12a2ab6eb3ff7a3ab443ac7048b62fcb8b9c658b082edb9abd14d

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8,<4.0
    - pip
    - poetry
  run:
    - python >=3.8,<4.0
    - pydantic >=1.7,<3.0
    - requests
    - pyyaml >=6.0

test:
  imports:
    - hera.workflows
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/argoproj-labs/hera-workflows
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Hera is an Argo Workflows Python SDK
  description: |
    Hera is an Argo Workflows Python SDK.
    Hera aims to make workflow construction and submission easy and accessible to everyone!
    Hera abstracts away workflow setup details while still maintaining a consistent vocabulary with Argo Workflows.
  doc_url: https://github.com/argoproj-labs/hera-workflows
  dev_url: https://github.com/argoproj-labs/hera-workflows

extra:
  recipe-maintainers:
    - harelwa
    - bchalk101
    - GuyPozner
