{% set name = "hera" %}
{% set version = "5.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hera-{{ version }}.tar.gz
  sha256: 5b4dcd63c0642a67054e6bb85a89143a7b6ae23606261c86d819f5a8ab2f6f47

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
  run:
    - python >={{ python_min }},<4.0
    - pydantic >=1.7,<3.0
    - requests
    - pyyaml >=6.0

test:
  imports:
    - hera.workflows
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/argoproj-labs/hera-workflows
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Hera is an Argo Workflows Python SDK
  description: |
    Hera is an Argo Workflows Python SDK.
    Hera aims to make workflow construction and submission easy and accessible to everyone!
    Hera abstracts away workflow setup details while still maintaining a consistent vocabulary with Argo Workflows.
  doc_url: https://github.com/argoproj-labs/hera-workflows
  dev_url: https://github.com/argoproj-labs/hera-workflows

extra:
  recipe-maintainers:
    - harelwa
    - bchalk101
    - GuyPozner
    - sagiahrac
